// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCandles = `-- name: ListCandles :many
SELECT id, symbol, open_time, open, high, low, close, volume, inside_bid, inside_ask, source, ingested_at
FROM candles
WHERE symbol = $1
  AND open_time >= $2
  AND open_time <= $3
ORDER BY open_time ASC
LIMIT $4
`

type ListCandlesParams struct {
	Symbol   string             `json:"symbol"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
	RowLimit int32              `json:"row_limit"`
}

func (q *Queries) ListCandles(ctx context.Context, arg ListCandlesParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, listCandles,
		arg.Symbol,
		arg.FromTime,
		arg.ToTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candle
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.OpenTime,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.InsideBid,
			&i.InsideAsk,
			&i.Source,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbols = `-- name: ListSymbols :many
SELECT DISTINCT symbol FROM candles ORDER BY symbol ASC
`

func (q *Queries) ListSymbols(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var symbol string
		if err := rows.Scan(&symbol); err != nil {
			return nil, err
		}
		items = append(items, symbol)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandle = `-- name: UpsertCandle :exec
INSERT INTO candles (
    symbol, open_time, open, high, low, close, volume, inside_bid, inside_ask, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (symbol, open_time) DO UPDATE SET
    open       = EXCLUDED.open,
    high       = EXCLUDED.high,
    low        = EXCLUDED.low,
    close      = EXCLUDED.close,
    volume     = EXCLUDED.volume,
    inside_bid = EXCLUDED.inside_bid,
    inside_ask = EXCLUDED.inside_ask,
    source     = EXCLUDED.source
`

type UpsertCandleParams struct {
	Symbol    string             `json:"symbol"`
	OpenTime  pgtype.Timestamptz `json:"open_time"`
	Open      int64              `json:"open"`
	High      int64              `json:"high"`
	Low       int64              `json:"low"`
	Close     int64              `json:"close"`
	Volume    int64              `json:"volume"`
	InsideBid int64              `json:"inside_bid"`
	InsideAsk int64              `json:"inside_ask"`
	Source    string             `json:"source"`
}

func (q *Queries) UpsertCandle(ctx context.Context, arg UpsertCandleParams) error {
	_, err := q.db.Exec(ctx, upsertCandle,
		arg.Symbol,
		arg.OpenTime,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.InsideBid,
		arg.InsideAsk,
		arg.Source,
	)
	return err
}
