// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candle struct {
	ID         int64              `json:"id"`
	Symbol     string             `json:"symbol"`
	OpenTime   pgtype.Timestamptz `json:"open_time"`
	Open       int64              `json:"open"`
	High       int64              `json:"high"`
	Low        int64              `json:"low"`
	Close      int64              `json:"close"`
	Volume     int64              `json:"volume"`
	InsideBid  int64              `json:"inside_bid"`
	InsideAsk  int64              `json:"inside_ask"`
	Source     string             `json:"source"`
	IngestedAt pgtype.Timestamptz `json:"ingested_at"`
}

type Order struct {
	ID          int64              `json:"id"`
	ClientUid   pgtype.UUID        `json:"client_uid"`
	Symbol      string             `json:"symbol"`
	Side        string             `json:"side"`
	Type        string             `json:"type"`
	LimitPrice  pgtype.Int8        `json:"limit_price"`
	Quantity    int64              `json:"quantity"`
	Mode        string             `json:"mode"`
	Strategy    pgtype.Text        `json:"strategy"`
	Status      string             `json:"status"`
	ExchangeRef pgtype.Text        `json:"exchange_ref"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Position struct {
	ID          int64              `json:"id"`
	Symbol      string             `json:"symbol"`
	Qty         int64              `json:"qty"`
	AvgCost     int64              `json:"avg_cost"`
	RealizedPnl int64              `json:"realized_pnl"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RiskState struct {
	ID         int64              `json:"id"`
	Day        pgtype.Date        `json:"day"`
	Halted     bool               `json:"halted"`
	HaltReason pgtype.Text        `json:"halt_reason"`
	SpentToday int64              `json:"spent_today"`
	LossToday  int64              `json:"loss_today"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SessionTrack struct {
	ID           int64              `json:"id"`
	SessionEvent int32              `json:"session_event"`
	Balance      int64              `json:"balance"`
	EventAt      pgtype.Timestamptz `json:"event_at"`
}
