// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPosition = `-- name: GetPosition :one
SELECT id, symbol, qty, avg_cost, realized_pnl, updated_at FROM positions WHERE symbol = $1
`

func (q *Queries) GetPosition(ctx context.Context, symbol string) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, symbol)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Qty,
		&i.AvgCost,
		&i.RealizedPnl,
		&i.UpdatedAt,
	)
	return i, err
}

const getRiskState = `-- name: GetRiskState :one
SELECT id, day, halted, halt_reason, spent_today, loss_today, updated_at FROM risk_state WHERE day = $1
`

func (q *Queries) GetRiskState(ctx context.Context, day pgtype.Date) (RiskState, error) {
	row := q.db.QueryRow(ctx, getRiskState, day)
	var i RiskState
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Halted,
		&i.HaltReason,
		&i.SpentToday,
		&i.LossToday,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (client_uid, symbol, side, type, limit_price, quantity, mode, strategy, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
RETURNING id, client_uid, symbol, side, type, limit_price, quantity, mode, strategy, status, exchange_ref, reason, created_at
`

type InsertOrderParams struct {
	ClientUid  pgtype.UUID `json:"client_uid"`
	Symbol     string      `json:"symbol"`
	Side       string      `json:"side"`
	Type       string      `json:"type"`
	LimitPrice pgtype.Int8 `json:"limit_price"`
	Quantity   int64       `json:"quantity"`
	Mode       string      `json:"mode"`
	Strategy   pgtype.Text `json:"strategy"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ClientUid,
		arg.Symbol,
		arg.Side,
		arg.Type,
		arg.LimitPrice,
		arg.Quantity,
		arg.Mode,
		arg.Strategy,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientUid,
		&i.Symbol,
		&i.Side,
		&i.Type,
		&i.LimitPrice,
		&i.Quantity,
		&i.Mode,
		&i.Strategy,
		&i.Status,
		&i.ExchangeRef,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertRiskState = `-- name: InsertRiskState :one
INSERT INTO risk_state (day) VALUES ($1)
ON CONFLICT (day) DO UPDATE SET updated_at = now()
RETURNING id, day, halted, halt_reason, spent_today, loss_today, updated_at
`

func (q *Queries) InsertRiskState(ctx context.Context, day pgtype.Date) (RiskState, error) {
	row := q.db.QueryRow(ctx, insertRiskState, day)
	var i RiskState
	err := row.Scan(
		&i.ID,
		&i.Day,
		&i.Halted,
		&i.HaltReason,
		&i.SpentToday,
		&i.LossToday,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOrders = `-- name: ListPendingOrders :many
SELECT id, client_uid, symbol, side, type, limit_price, quantity, mode, strategy, status, exchange_ref, reason, created_at FROM orders WHERE status = 'pending' AND mode = 'live' ORDER BY id ASC
`

func (q *Queries) ListPendingOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listPendingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ClientUid,
			&i.Symbol,
			&i.Side,
			&i.Type,
			&i.LimitPrice,
			&i.Quantity,
			&i.Mode,
			&i.Strategy,
			&i.Status,
			&i.ExchangeRef,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRiskHalted = `-- name: SetRiskHalted :exec
UPDATE risk_state SET halted = $2, halt_reason = $3, updated_at = now() WHERE day = $1
`

type SetRiskHaltedParams struct {
	Day        pgtype.Date `json:"day"`
	Halted     bool        `json:"halted"`
	HaltReason pgtype.Text `json:"halt_reason"`
}

func (q *Queries) SetRiskHalted(ctx context.Context, arg SetRiskHaltedParams) error {
	_, err := q.db.Exec(ctx, setRiskHalted, arg.Day, arg.Halted, arg.HaltReason)
	return err
}

const settleOrder = `-- name: SettleOrder :exec
UPDATE orders
SET status = $2, exchange_ref = $3, reason = $4
WHERE id = $1
`

type SettleOrderParams struct {
	ID          int64       `json:"id"`
	Status      string      `json:"status"`
	ExchangeRef pgtype.Text `json:"exchange_ref"`
	Reason      pgtype.Text `json:"reason"`
}

func (q *Queries) SettleOrder(ctx context.Context, arg SettleOrderParams) error {
	_, err := q.db.Exec(ctx, settleOrder,
		arg.ID,
		arg.Status,
		arg.ExchangeRef,
		arg.Reason,
	)
	return err
}

const updateRiskSpentLoss = `-- name: UpdateRiskSpentLoss :exec
UPDATE risk_state
SET spent_today = spent_today + $2, loss_today = loss_today + $3, updated_at = now()
WHERE day = $1
`

type UpdateRiskSpentLossParams struct {
	Day        pgtype.Date `json:"day"`
	SpentToday int64       `json:"spent_today"`
	LossToday  int64       `json:"loss_today"`
}

func (q *Queries) UpdateRiskSpentLoss(ctx context.Context, arg UpdateRiskSpentLossParams) error {
	_, err := q.db.Exec(ctx, updateRiskSpentLoss, arg.Day, arg.SpentToday, arg.LossToday)
	return err
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (symbol, qty, avg_cost, realized_pnl, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (symbol) DO UPDATE SET
    qty = EXCLUDED.qty,
    avg_cost = EXCLUDED.avg_cost,
    realized_pnl = EXCLUDED.realized_pnl,
    updated_at = now()
`

type UpsertPositionParams struct {
	Symbol      string `json:"symbol"`
	Qty         int64  `json:"qty"`
	AvgCost     int64  `json:"avg_cost"`
	RealizedPnl int64  `json:"realized_pnl"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.Exec(ctx, upsertPosition,
		arg.Symbol,
		arg.Qty,
		arg.AvgCost,
		arg.RealizedPnl,
	)
	return err
}
