// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"
)

const insertSessionTrack = `-- name: InsertSessionTrack :one
INSERT INTO session_tracks (session_event, balance, event_at)
VALUES ($1, $2, now())
RETURNING id, session_event, balance, event_at
`

type InsertSessionTrackParams struct {
	SessionEvent int32 `json:"session_event"`
	Balance      int64 `json:"balance"`
}

func (q *Queries) InsertSessionTrack(ctx context.Context, arg InsertSessionTrackParams) (SessionTrack, error) {
	row := q.db.QueryRow(ctx, insertSessionTrack, arg.SessionEvent, arg.Balance)
	var i SessionTrack
	err := row.Scan(
		&i.ID,
		&i.SessionEvent,
		&i.Balance,
		&i.EventAt,
	)
	return i, err
}
