-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";
-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';
-- Create "candles" table
CREATE TABLE "public"."candles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "symbol" text NOT NULL,
  "open_time" timestamptz NOT NULL,
  "open" bigint NOT NULL,
  "high" bigint NOT NULL,
  "low" bigint NOT NULL,
  "close" bigint NOT NULL,
  "volume" bigint NOT NULL,
  "inside_bid" bigint NOT NULL,
  "inside_ask" bigint NOT NULL,
  "source" text NOT NULL DEFAULT 'ticker',
  "ingested_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create index "candles_symbol_open_time_key" to table: "candles"
CREATE UNIQUE INDEX "candles_symbol_open_time_key" ON "public"."candles" ("symbol", "open_time");
-- Create "orders" table
CREATE TABLE "public"."orders" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "client_uid" uuid NOT NULL,
  "symbol" text NOT NULL,
  "side" text NOT NULL,
  "type" text NOT NULL,
  "limit_price" bigint NULL,
  "quantity" bigint NOT NULL,
  "mode" text NOT NULL,
  "strategy" text NULL,
  "status" text NOT NULL,
  "exchange_ref" text NULL,
  "reason" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create index "orders_client_uid_key" to table: "orders"
CREATE UNIQUE INDEX "orders_client_uid_key" ON "public"."orders" ("client_uid");
-- Create "positions" table
CREATE TABLE "public"."positions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "symbol" text NOT NULL,
  "qty" bigint NOT NULL DEFAULT 0,
  "avg_cost" bigint NOT NULL DEFAULT 0,
  "realized_pnl" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create index "positions_symbol_key" to table: "positions"
CREATE UNIQUE INDEX "positions_symbol_key" ON "public"."positions" ("symbol");
-- Create "risk_state" table
CREATE TABLE "public"."risk_state" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "day" date NOT NULL,
  "halted" boolean NOT NULL DEFAULT false,
  "halt_reason" text NULL,
  "spent_today" bigint NOT NULL DEFAULT 0,
  "loss_today" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create index "risk_state_day_key" to table: "risk_state"
CREATE UNIQUE INDEX "risk_state_day_key" ON "public"."risk_state" ("day");
